server:
  port: 8080

spring:
  application:
    name: knot-ai-gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/knot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      #data-locations: classpath:db/data.sql
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql
  default-count: true

springdoc:
  api-docs:
    path: /api/docs/openapi.json
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: org.chobit.knot.gateway.controller
  default-flat-param-object: true

