server:
  port: 8080

spring:
  application:
    name: knot-ai-gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/knot_ai_gateway?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

